apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: prom-operator
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-02-07T20:47:42Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: prom-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 9.3.1
    helm.sh/chart: grafana-6.50.2
  name: prom-operator-grafana
  namespace: default
  resourceVersion: "37191458"
  uid: a803a63b-69a3-467f-9522-70f3135c2c28
spec:
  endpoints:
  - honorLabels: true
    path: /metrics
    port: http-web
    scheme: http
    scrapeTimeout: 30s
  jobLabel: prom-operator
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/instance: prom-operator
      app.kubernetes.io/name: grafana
